# Generated by Django 5.0.6 on 2024-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='summary',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='transcription',
            field=models.JSONField(blank=True),
        ),
    ]
